language: node_js

addons:
  ssh_known_hosts: ${HOST}:${PORT}

node_js:
  - '8'

sudo: false

branches:
  only:
  - master

cache:
  dirctories:
  - node_modules

install:
   - npm install

script:
  - npm run build

after_script:
  - scp -P ${PORT} -r ./dist/. ${USER}@${HOST}:/var/www/yanding

before_install:
  - openssl aes-256-cbc -K $encrypted_3b2878a3d558_key -iv $encrypted_3b2878a3d558_iv -in travis.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa